ATTACH DATABASE 'streaming_data.db' As 'streaming_data';

CREATE TABLE FULL_NSE_ACC(
    ID_DATE TEXT PRIMARY KEY NOT NULL,
    LAST_PRICE REAL NOT NULL,
    LAST_QUANTITY INTEGER NOT NULL,
    AVERAGE_PRICE REAL NOT NULL,
    VOLUME INTEGER NOT NULL,
    BUY_QUANTITY INTEGER NOT NULL,
    SELL_QUANTITY INTEGER NOT NULL,
    OPEN_PRICE REAL NOT NULL,
    HIGH_PRICE REAL NOT NULL,
    CLOSE_PRICE REAL NOT NULL,
    LOW_PRICE REAL NOT NULL,
    CHANGE REAL NOT NULL,
    LAST_TRADE_TIME TEXT NOT NULL,
    OPEN_INTEREST INTEGER NOT NULL,
    OPEN_INTEREST_HIGH INTEGER NOT NULL,
    OPEN_INTEREST_LOW INTEGER NOT NULL
);

CREATE TABLE FULL_NSE_ACC_MARKET_DEPTH_BUY(
    ID_DATE TEXT NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE REAL NOT NULL,
    ORDERS INTEGER NOT NULL,
    PRIMARY KEY (ID_DATE,QUANTITY,PRICE,ORDERS)
);

CREATE TABLE FULL_NSE_ACC_MARKET_DEPTH_SELL(
    ID_DATE TEXT NOT NULL,
    QUANTITY INTEGER NOT NULL,
    PRICE REAL NOT NULL,
    ORDERS INTEGER NOT NULL,
    PRIMARY KEY (ID_DATE,QUANTITY,PRICE,ORDERS)
);
